name: Greetings

on: [pull_request, issues]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        uses: actions/github-script@v7
        with:
          script: |
            if (github.context.eventName === 'pull_request') {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: "Hello! Thanks for your contribution."
              });
            }